# Generated by Django 4.1.9 on 2023-05-05 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ('title',)},
        ),
        migrations.RemoveField(
            model_name='userfilmvisualization',
            name='visualization',
        ),
    ]
